# ClothingService/Dockerfile
FROM openjdk:17
EXPOSE 8082
COPY target/ClothingService-0.0.1-SNAPSHOT.jar ClothingService-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "/ClothingService-0.0.1-SNAPSHOT.jar"]